import { useEffect, useState } from "react";
import { View, Text, ScrollView } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import Constants from "expo-constants";
import { isPro, restorePurchases, subscriptionsMockMode } from "@/services/subscriptions";
import { PrimaryButton } from "@/components/PrimaryButton";

export default function Settings() {
  const router = useRouter();
  const [pro, setPro] = useState(false);

  useEffect(() => {
    isPro().then(setPro);
  }, []);

  return (
    <SafeAreaView className="flex-1 bg-white">
      <ScrollView contentContainerStyle={{ padding: 24, gap: 24 }}>
        <View>
          <Text className="text-lg font-bold text-leaf-900 mb-2">Subscription</Text>
          <Text className="text-sm text-gray-600 mb-3">
            Status: {pro ? "PlantApp Pro ✅" : subscriptionsMockMode ? "Free (dev mode)" : "Free"}
          </Text>
          {!pro && <PrimaryButton label="✨ Upgrade to Pro" onPress={() => router.push("/paywall")} />}
          {!subscriptionsMockMode && (
            <View className="mt-2">
              <PrimaryButton
                label="Restore purchases"
                variant="secondary"
                onPress={() => restorePurchases().then(setPro)}
              />
            </View>
          )}
        </View>

        <View>
          <Text className="text-lg font-bold text-leaf-900 mb-2">About</Text>
          <Text className="text-sm text-gray-600">PlantApp v{Constants.expoConfig?.version}</Text>
          <Text className="text-xs text-gray-400 mt-2">
            Plant identification, care, health and edibility guidance is generated by AI and may occasionally be
            wrong. Never eat a wild plant based solely on this app — always confirm with a local expert first.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
